# Generated by Django 5.1.1 on 2024-10-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XYZ', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivarity',
            name='desc',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='chaivarity',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
